name: Update release title

on:
  push:
    branches:
      - main

jobs:
  update-release-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find plugin folders
        id: find_plugin_folders
        run: |
          echo "::set-output name=plugin_dirs::$(find . -maxdepth 2 -type f -name "mcdreforged.plugin.json" -print0 \
            | xargs -0 -I {} dirname {})"
        shell: bash

      - name: Check version number
        id: check_version_number
        run: |
          plugin_dirs="${{ steps.find_plugin_folders.outputs.plugin_dirs }}"
          echo "Plugin directories: $plugin_dirs"
          for plugin_dir in $plugin_dirs; do
            version=$(jq -r '.version' "$plugin_dir/mcdreforged.plugin.json")
            if [ -z "$version" ]; then
              echo "Version number not found in $plugin_dir"
              continue
            fi
            git fetch --tags
            latest_release_tag=$(git describe --tags --abbrev=0 --always)
            if [ "$latest_release_tag" == "$version" ]; then
              echo "Version $version has already been released"
            elif [ "$(printf '%s\n' "$version" "$latest_release_tag" | sort -V | head -n1)" != "$version" ]; then
              echo "Version $version is older than the latest release ($latest_release_tag)"
            else
              echo "Version $version is newer than the latest release ($latest_release_tag)"
            fi
          done
        env:
          PLUGIN_DIR: ${{ steps.find_plugin_folders.outputs.plugin_dirs }}

      - name: Set release title
        id: set_release_title
        run: |
          plugin_dir="${{ env.PLUGIN_DIR }}"
          version=$(jq -r '.version' "$plugin_dir/mcdreforged.plugin.json")
          echo "::set-output name=release_title::$(basename $plugin_dir)-v${version}"
        env:
          PLUGIN_DIR: ${{ steps.find_plugin_folders.outputs.plugin_dirs }}

      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLUGIN_DIR: ${{ steps.find_plugin_folders.outputs.plugin_dirs }}
        with:
          tag_name: ${{ env.PLUGIN_DIR }}-v${{ steps.set_release_title.outputs.release_title }}
          release_name: ${{ env.PLUGIN_DIR }}-v${{ steps.set_release_title.outputs.release_title }}
          body: |
            Release for ${{ env.PLUGIN_DIR }} version ${{ steps.set_release_title.outputs.release_title }}
          draft: false
          prerelease: false
        
